package org.pircbotx.hooks.managers;

import org.pircbotx.hooks.Event;
import org.pircbotx.hooks.Listener;

/**
 * Handle exceptions from listeners
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */
public interface ManagerExceptionHandler {
	/**
	 * Called when any listener throws an exception when executing the specified event
	 * @param listener Listener that was being executed
	 * @param event Event that was dispatched
	 * @param exception Exception that was generated by the Listener
	 */
	public void onException(Listener listener, Event event, Throwable exception);
}
