/**
 * Copyright (C) 2010 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.pircbotx.hooks;

import org.pircbotx.Channel;
import org.pircbotx.User;
import org.pircbotx.hooks.helpers.BaseEvent;
import org.pircbotx.hooks.helpers.BaseListener;
import org.pircbotx.hooks.helpers.BaseSimpleListener;

/**
 * Called whenever an ACTION is sent from a user.  E.g.
 * such events generated by typing "/me goes shopping" in most IRC clients.
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */
public class Action {
	/**
	 * Simple listener that takes event parameters as parameters. See 
	 * {@link Action} for an explanation on use 
	 * @see Action 
	 */
	public static interface SimpleListener extends BaseSimpleListener {
		/**
		 * Simple Listener for Action Events. See {@link Action} for a complete description on when
		 * this is called.
		 * @param source The user that sent the message
		 * @param target The target channel of the action. A value of <code>null</code>
		 *               means the target is us.
		 * @param action The action carried out by the user.
		 * @see Action
		 * @see SimpleListener
		 */
		public void onAction(User source, User userTarget, Channel chanTarget, String action);
	}

	/**
	 * Listener that receives an event. See {@link Action} for an explanation 
	 * on use and {@link Event} for an explanation on the event. 
	 * @see Action 
	 * @see Event 
	 */
	public static interface Listener extends BaseListener {
		/**
		 * Listener for Action Events. See {@link Action} for a complete description on when
		 * this is called.
		 * @see Action
		 * @see Listener
		 */
		public void onAction(Event event);
	}

	/**
	 * Event that is passed to all listeners that contains all the given
	 * information. See {@link Action} for an explanation on when this is created
	 * <p>
	 * <b>Note:<b> This class and all its subclasses are immutable since
	 * data should not change after creation
	 * @see Action 
	 * @see Listener
	 */
	public static class Event implements BaseEvent {
		protected final long timestamp;
		protected final User source;
		protected final Channel target;
		protected final String action;

		/**
		 * Default constructor to setup object. Timestamp is automatically set
		 * to current time as reported by {@link System#currentTimeMillis() }
		 * @param source The user that sent the message
		 * @param target The target channel of the action. A value of <code>null</code>
		 *               means the target is us.
		 * @param action The action carried out by the user.
		 */
		public Event(User source, Channel target, String action) {
			this.timestamp = System.currentTimeMillis();
			this.source = source;
			this.target = target;
			this.action = action;
		}

		public long getTimestamp() {
			return timestamp;
		}

		/**
		 * Get the value of target
		 *
		 * @return the value of target
		 */
		public Channel getTarget() {
			return target;
		}

		/**
		 * Get the value of action
		 *
		 * @return the value of action
		 */
		public String getAction() {
			return action;
		}

		public User getSource() {
			return source;
		}
	}
}
